In [ ]:
import numpy as np

In [4]:
data = np.array([1,2,3,4,5,6])
data

array([1, 2, 3, 4, 5, 6])

In [5]:
sum = data.sum()
sum

21

In [6]:
mean = sum/len(data)
mean

3.5

In [7]:
data1 = np.array(range(1,16))
data1

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15])

In [8]:
sum1 = data1.sum()
sum1

120

In [9]:
mean1 = sum1/len(data1)
mean1

8.0

In [11]:
y = np.array(range(1000,2001))
y

array([1000, 1001, 1002, ..., 1998, 1999, 2000])

In [13]:
sumOfY = y.sum()
sumOfY

1501500

In [14]:
meanOfY = sumOfY/len(y)
meanOfY

1500.0